# ========= Stage 1: Build Stage ==================
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package -DskipTests

# ======== Stage2: Runtime Stage ========
FROM eclipse-temurin:17-jre
WORKDIR /app

RUN groupadd -r appgroup && useradd -r -g appgroup appuser
USER appuser

COPY --from=build /app/target/w4d2-0.0.2.jar app.jar

EXPOSE 8080

ENV DB_URL="jdbc:mysql://host.docker.internal:3306/course?createDatabaseIfNotExist=true&serverTimezone=UTC"
ENV DB_USERNAME=root
ENV DB_PASS=

ENTRYPOINT ["java", "-jar", "/app/app.jar"]